name: Release Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build All Versions
      run: make build

    - name: Determine Version Number
      id: version
      run: |
        VERSION_DATE=$(date +%Y.%m.%d)
        echo "TAG_NAME=$VERSION_DATE" >> $GITHUB_OUTPUT
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.TAG_NAME }}
        name: Release - ${{ steps.version.outputs.TAG_NAME }}
        body_path: MAJOR_CHANGELOG.md
        make_latest: true
        token: ${{ secrets.GIT_TOKEN }}
        files: |
          build/simple-feeds-linux-amd64.so
          build/simple-feeds-linux-arm-7.so
          build/simple-feeds-linux-arm64.so
